"""Render the ingestion report (docs/ingestion_report.md) from per-document results."""

from datetime import datetime, timezone

from ingestion.common import CHUNK_OVERLAP_TOKENS, CHUNK_SIZE_TOKENS


def _pages(pages: list[int]) -> str:
    return ", ".join(map(str, pages)) if pages else "none"


def render(results: list[dict], embedding_model: str, embedded: bool, vector_total: int | None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    out = [
        "# Ingestion report",
        "",
        f"_Generated by `python -m ingestion.run_ingestion` on {now}. Regenerated on every run; hand-written "
        "findings live in [ingestion_manual_qa.md](./ingestion_manual_qa.md)._",
        "",
        "## Configuration",
        "",
        "| Setting | Value |",
        "|---|---|",
        f"| Chunk size | {CHUNK_SIZE_TOKENS} tokens (embedding-model tokenizer; budget covers section heading + text) |",
        f"| Chunk overlap | {CHUNK_OVERLAP_TOKENS} tokens (prose only; tables and lists are atomic) |",
        f"| Embedding model | `{embedding_model}` (384-d, normalised) |",
        f"| Embedded + upserted | {'yes' if embedded else 'no (dry run)'} |",
        f"| Points in vector store | {vector_total if vector_total is not None else 'n/a'} |",
        "",
        "## Per-document summary",
        "",
        "| Document | Extractor | Pages | Chunks | Avg tokens | Min | Max | Sections | Tables | Lists | Tiny (<20 tok) | Over 512 |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        s = r["stats"]
        out.append(
            f"| {r['name']} | {r['extractor']} | {r['pages']} | {s['chunks']} | {s['tokens_avg']} | "
            f"{s['tokens_min']} | {s['tokens_max']} | {s['sections']} | {s['by_kind'].get('table', 0)} | "
            f"{s['by_kind'].get('list', 0)} | {s['tiny_chunks']} | {r['over_limit']} |"
        )
    out += ["", "## Page-level problems", "", "| Document | Empty / near-empty pages | Garbled pages (U+FFFD) | Excluded pages |", "|---|---|---|---|"]
    for r in results:
        out.append(f"| {r['name']} | {_pages(r['empty_pages'])} | {_pages(r['garbled_pages'])} | {_pages(r['excluded_pages'])} |")
    out += [
        "",
        "Empty pages are mostly cover art or full-page figures with no text layer (no OCR is applied). "
        "Excluded pages are tables of contents / lists of tables, left out so their entries cannot outrank real content.",
        "",
        "## Numeric fidelity (PDF text layer vs extracted blocks)",
        "",
        "`missing` = a number on the source page that appears nowhere in the extraction (lost data, or a removed running "
        "header/footer such as a page number). `not in source` = a number in an extracted table that is not on its source "
        "page (altered or invented) and must be zero.",
        "",
        "| Document | Numbers in source | Missing | Table numbers not in source |",
        "|---|---|---|---|",
    ]
    for r in results:
        f = r["fidelity"]
        if not f.get("checked"):
            out.append(f"| {r['name']} | n/a (HTML) | n/a | n/a |")
            continue
        altered = sum(len(v) for v in f["table_numbers_not_in_source"].values())
        out.append(f"| {r['name']} | {f['raw_numbers']} | {f['missing_numbers']} | {altered} |")
    for r in results:
        f = r["fidelity"]
        if f.get("table_numbers_not_in_source"):
            out += ["", f"**{r['name']}** — table numbers not found on the source page:"]
            out += [f"- page {p}: {', '.join(v[:15])}" for p, v in sorted(f["table_numbers_not_in_source"].items())]
    out += ["", "## Sections detected", ""]
    for r in results:
        out += [f"<details><summary>{r['name']} — {r['stats']['sections']} sections</summary>", ""]
        out += [f"- {label} ({n})" for label, n in r["section_counts"][:60]]
        if len(r["section_counts"]) > 60:
            out.append(f"- … and {len(r['section_counts']) - 60} more")
        out += ["", "</details>", ""]
    out += [
        "## Registry year check",
        "",
        "Dates found inside the downloaded files, against the `year` in `document_registry.json` (which is cited to users). "
        "File dates show when a file was produced, not necessarily its edition year, so mismatches are for review, not errors.",
        "",
        "| Document | Registry year | Evidence in file | Consistent |",
        "|---|---|---|---|",
    ]
    for r in results:
        out.append(f"| {r['name']} | {r['year']} | {'; '.join(r['year_evidence']) or 'none found'} | {'yes' if r['year_ok'] else '**review**'} |")
    out += ["", "## Warnings", ""]
    warnings = [w for r in results for w in r["warnings"]]
    out += [f"- {w}" for w in warnings] or ["- none"]
    return "\n".join(out) + "\n"
